// biome-ignore-all lint: generated by TanStack Router

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/root";
import { Route as workflowsRouteImport } from "./routes/workflows";
import { Route as reposRouteImport } from "./routes/repos";
import { Route as pulseRouteImport } from "./routes/pulse";
import { Route as onboardingRouteImport } from "./routes/onboarding";
import { Route as liveRouteImport } from "./routes/live";
import { Route as inboxRouteImport } from "./routes/inbox";
import { Route as communityRouteImport } from "./routes/community";
import { Route as chatRouteImport } from "./routes/chat";
import { Route as agentsRouteImport } from "./routes/agents";
import { Route as indexRouteImport } from "./routes/index";
import { Route as reposDotrepoIdRouteImport } from "./routes/repos.$repoId";
import { Route as inviteDotcodeRouteImport } from "./routes/invite.$code";
import { Route as reposDotrepoIdDotblobDotsplatRouteImport } from "./routes/repos.$repoId.blob.$";

const workflowsRoute = workflowsRouteImport.update({
  id: "/workflows",
  path: "/workflows",
  getParentRoute: () => rootRouteImport,
} as any);
const reposRoute = reposRouteImport.update({
  id: "/repos",
  path: "/repos",
  getParentRoute: () => rootRouteImport,
} as any);
const pulseRoute = pulseRouteImport.update({
  id: "/pulse",
  path: "/pulse",
  getParentRoute: () => rootRouteImport,
} as any);
const onboardingRoute = onboardingRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => rootRouteImport,
} as any);
const liveRoute = liveRouteImport.update({
  id: "/live",
  path: "/live",
  getParentRoute: () => rootRouteImport,
} as any);
const inboxRoute = inboxRouteImport.update({
  id: "/inbox",
  path: "/inbox",
  getParentRoute: () => rootRouteImport,
} as any);
const communityRoute = communityRouteImport.update({
  id: "/community",
  path: "/community",
  getParentRoute: () => rootRouteImport,
} as any);
const chatRoute = chatRouteImport.update({
  id: "/chat",
  path: "/chat",
  getParentRoute: () => rootRouteImport,
} as any);
const agentsRoute = agentsRouteImport.update({
  id: "/agents",
  path: "/agents",
  getParentRoute: () => rootRouteImport,
} as any);
const indexRoute = indexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const reposDotrepoIdRoute = reposDotrepoIdRouteImport.update({
  id: "/repos/$repoId",
  path: "/repos/$repoId",
  getParentRoute: () => rootRouteImport,
} as any);
const inviteDotcodeRoute = inviteDotcodeRouteImport.update({
  id: "/invite/$code",
  path: "/invite/$code",
  getParentRoute: () => rootRouteImport,
} as any);
const reposDotrepoIdDotblobDotsplatRoute =
  reposDotrepoIdDotblobDotsplatRouteImport.update({
    id: "/repos/$repoId/blob/$",
    path: "/repos/$repoId/blob/$",
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof indexRoute;
  "/agents": typeof agentsRoute;
  "/chat": typeof chatRoute;
  "/community": typeof communityRoute;
  "/inbox": typeof inboxRoute;
  "/live": typeof liveRoute;
  "/onboarding": typeof onboardingRoute;
  "/pulse": typeof pulseRoute;
  "/repos": typeof reposRoute;
  "/workflows": typeof workflowsRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRoutesByTo {
  "/": typeof indexRoute;
  "/agents": typeof agentsRoute;
  "/chat": typeof chatRoute;
  "/community": typeof communityRoute;
  "/inbox": typeof inboxRoute;
  "/live": typeof liveRoute;
  "/onboarding": typeof onboardingRoute;
  "/pulse": typeof pulseRoute;
  "/repos": typeof reposRoute;
  "/workflows": typeof workflowsRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof indexRoute;
  "/agents": typeof agentsRoute;
  "/chat": typeof chatRoute;
  "/community": typeof communityRoute;
  "/inbox": typeof inboxRoute;
  "/live": typeof liveRoute;
  "/onboarding": typeof onboardingRoute;
  "/pulse": typeof pulseRoute;
  "/repos": typeof reposRoute;
  "/workflows": typeof workflowsRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/agents"
    | "/chat"
    | "/community"
    | "/inbox"
    | "/live"
    | "/onboarding"
    | "/pulse"
    | "/repos"
    | "/workflows"
    | "/invite/$code"
    | "/repos/$repoId"
    | "/repos/$repoId/blob/$";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/agents"
    | "/chat"
    | "/community"
    | "/inbox"
    | "/live"
    | "/onboarding"
    | "/pulse"
    | "/repos"
    | "/workflows"
    | "/invite/$code"
    | "/repos/$repoId"
    | "/repos/$repoId/blob/$";
  id:
    | "__root__"
    | "/"
    | "/agents"
    | "/chat"
    | "/community"
    | "/inbox"
    | "/live"
    | "/onboarding"
    | "/pulse"
    | "/repos"
    | "/workflows"
    | "/invite/$code"
    | "/repos/$repoId"
    | "/repos/$repoId/blob/$";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute;
  agentsRoute: typeof agentsRoute;
  chatRoute: typeof chatRoute;
  communityRoute: typeof communityRoute;
  inboxRoute: typeof inboxRoute;
  liveRoute: typeof liveRoute;
  onboardingRoute: typeof onboardingRoute;
  pulseRoute: typeof pulseRoute;
  reposRoute: typeof reposRoute;
  workflowsRoute: typeof workflowsRoute;
  inviteDotcodeRoute: typeof inviteDotcodeRoute;
  reposDotrepoIdRoute: typeof reposDotrepoIdRoute;
  reposDotrepoIdDotblobDotsplatRoute: typeof reposDotrepoIdDotblobDotsplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/workflows": {
      id: "/workflows";
      path: "/workflows";
      fullPath: "/workflows";
      preLoaderRoute: typeof workflowsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repos": {
      id: "/repos";
      path: "/repos";
      fullPath: "/repos";
      preLoaderRoute: typeof reposRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/pulse": {
      id: "/pulse";
      path: "/pulse";
      fullPath: "/pulse";
      preLoaderRoute: typeof pulseRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/onboarding": {
      id: "/onboarding";
      path: "/onboarding";
      fullPath: "/onboarding";
      preLoaderRoute: typeof onboardingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/live": {
      id: "/live";
      path: "/live";
      fullPath: "/live";
      preLoaderRoute: typeof liveRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/inbox": {
      id: "/inbox";
      path: "/inbox";
      fullPath: "/inbox";
      preLoaderRoute: typeof inboxRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/community": {
      id: "/community";
      path: "/community";
      fullPath: "/community";
      preLoaderRoute: typeof communityRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/chat": {
      id: "/chat";
      path: "/chat";
      fullPath: "/chat";
      preLoaderRoute: typeof chatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/agents": {
      id: "/agents";
      path: "/agents";
      fullPath: "/agents";
      preLoaderRoute: typeof agentsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof indexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repos/$repoId": {
      id: "/repos/$repoId";
      path: "/repos/$repoId";
      fullPath: "/repos/$repoId";
      preLoaderRoute: typeof reposDotrepoIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/invite/$code": {
      id: "/invite/$code";
      path: "/invite/$code";
      fullPath: "/invite/$code";
      preLoaderRoute: typeof inviteDotcodeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repos/$repoId/blob/$": {
      id: "/repos/$repoId/blob/$";
      path: "/repos/$repoId/blob/$";
      fullPath: "/repos/$repoId/blob/$";
      preLoaderRoute: typeof reposDotrepoIdDotblobDotsplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  agentsRoute: agentsRoute,
  chatRoute: chatRoute,
  communityRoute: communityRoute,
  inboxRoute: inboxRoute,
  liveRoute: liveRoute,
  onboardingRoute: onboardingRoute,
  pulseRoute: pulseRoute,
  reposRoute: reposRoute,
  workflowsRoute: workflowsRoute,
  inviteDotcodeRoute: inviteDotcodeRoute,
  reposDotrepoIdRoute: reposDotrepoIdRoute,
  reposDotrepoIdDotblobDotsplatRoute: reposDotrepoIdDotblobDotsplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
