-- Generated by node deploy/supabase/migration-manifest.mjs; do not edit.
WITH expected(version, checksum) AS (VALUES
  (1::bigint, decode('dbc16fbf139a47d526975a727e6349aa9800a8ffec0a9f040a7f4e545d413e50a32160171d4cb112bf3671823eea7075', 'hex')),
  (2::bigint, decode('49c1e203577698af725d2db237e25da3cf928ba19b5a07cf14f2bcd1d22d486a3b53263f025040273e393be16145e270', 'hex')),
  (3::bigint, decode('d0953a3ac68d2c7c7305c91b0c3ac122bbdc7cc25de0a28f30462d2632d9ccf26256dfea031c0ff690f9e1b5c0dae17d', 'hex')),
  (4::bigint, decode('5c5108f23d2866cd30e10d15d10b9fa75383ac86985d1be0757f32e3dead6f7caecce30c499eea3221b4d114cd99df6a', 'hex')),
  (5::bigint, decode('84cf1c768d80480a07bea5b43b83b83d2ff0c3809d2011dcfb751be6a34177c7aab67a9cc2ae8968f50a513edd7d8e83', 'hex')),
  (6::bigint, decode('9e5bbfa7469aefc0158f9f67208bdbd54c5eb3c821ae64f33fcbc2b38680afae47ab80d1fb5fda53f59cd8d68422c0d2', 'hex')),
  (7::bigint, decode('939ac3ebe69d9db5dfe2e59ed1c9251270a27559fc74ad36aecf9761994c32e808f77220489322d37ce557c3de56cfca', 'hex')),
  (8::bigint, decode('f182146b6470c11c78bd4f6a285e078df6072958eb9f264d0432dd47b9e2889dd36287ca730100759542017f1786ed67', 'hex')),
  (9::bigint, decode('5797443ecc13ce7bd4cfd5707d8ce44a37e104b0fab0355b7c4d620667943ee357141610cf95bb5cb27f6a3d3020022f', 'hex')),
  (10::bigint, decode('84748c2160148d3674f4e15325aedc19a8f7300b1f465b64d06ef0c43cb4c96412b41a99dab4a28db8247dc18072e383', 'hex')),
  (11::bigint, decode('d6fcbfe79e22e7c73caee36cba13c7feb5daf690fdc6957264c897f25678deb8dd220a4b422030570d475fe14d63f342', 'hex')),
  (12::bigint, decode('b95c2e08388d1f698f62a3cce948ec108300fb3b4b2b719803ecbc4af4f8cc07d5ad75b61d7287d1a91aa020938b1d35', 'hex')),
  (13::bigint, decode('6db1b972e28884665c49c5c926fb5464f104db853df311c97613e339b7ed82b847e120487c12719229be48ecb3635fc7', 'hex')),
  (14::bigint, decode('08755814a36a4f8494f7f48bce6d37a429b710a1902d0ed3569d5533b460cfd355098a3dad662320f9dd5cdec37ff0c2', 'hex')),
  (15::bigint, decode('74c3b952090efe211d08da10a474de0e1ec9b02e2c22e6503210e45aff07de1667afc95cf0e10eb6b4bafe2f0864d906', 'hex')),
  (16::bigint, decode('39de24bdf7c26f172af58972993c379a50c81d8755187f23deabd9919ddba11c47faff3d69d2bdd42bf9096ca2441c81', 'hex')),
  (17::bigint, decode('2788f2b8bf2347ccaea0d15bd602b863e1be721b2cc292d433bf64ca66cdbbb9fa87739e22eab94da03e4d34e7be426d', 'hex')),
  (18::bigint, decode('f6a16ba98bf84174088684d19cc33b0efc436635723823f69429fafe1389b60e9432ceb7107afdc53900b46ffc4e47c9', 'hex')),
  (19::bigint, decode('a9c2b378c0650bcaa9004f2f34a96b4eb41e02cdf6fc0797b128d706ce07bfa51725a66af63d9f5084d61e9a731c1049', 'hex')),
  (20::bigint, decode('06409e8657ce06941e1aca68049405d48beb23be83ac971fd6aee358e5eac119f579730d0e0904409abb43ce146124d8', 'hex')),
  (21::bigint, decode('37d7ff757ecd2e6eda79830a80725efe81ca76eb46291891ebe0380ad3717dc58e9c1d203b656812dfda7d8ed2e9f2f2', 'hex')),
  (22::bigint, decode('82a015291aa8b9a50dbc8d7308a865b63140d39a5581694428b7d038086da8cceba7f6709db270fa8aac3d546e32da0f', 'hex')),
  (23::bigint, decode('fb1876d1af9738342bc24b3e0ad8de73e45900786f15283e338d59c81f05548cef2734ffb2e243120aff23957310e0bc', 'hex')),
  (24::bigint, decode('aaf2084176d409cb63015acce2d4d13a730d3f8ca060d0fb262b6d1805b0c33c36a07528691af2240be76e2ea4fe61f3', 'hex')),
  (25::bigint, decode('d4fdfc8bc8c9d75f7b812f40d533af80de1053fdd0d95c99b6ff6376e7d7090a8b514ef4e0e9d31aba258e6e7833b1c5', 'hex')),
  (26::bigint, decode('d08e2f660ed70d11a765c710d8c6cb448f6e151b3aa46b75ddd47be88f4df0f355e923794c25be2aa5d566a51a04059e', 'hex')),
  (27::bigint, decode('a0d196710d689af3f5b9d0257aee31aa2f435a06b8663c206a4d5cf819c979e3f36740d192901785e013a56e99447d9b', 'hex')),
  (28::bigint, decode('32ac3a3abf13343683edc353a361feee1d6b8ebb2d997805188599a0bde9b0a4aa18a99d61f47df41f5a1778bb9a261e', 'hex')),
  (29::bigint, decode('394b003cced50dc7afa129b543baf1afa0ffda29c29910dfaf50e893427fe1c0b588c98df327b024cf9e2598ac35bed1', 'hex')),
  (30::bigint, decode('d5d4e3ad0ac497ae16bce16da943db740d59befedb9768c9934bd8066baf5f88b5db64428082c751f34e591d32b02649', 'hex')),
  (31::bigint, decode('39941ad9cc326fb6896fb14f230fe37cc9db0c922fdedcbad8455bc6cf03ec90a03109ae5af4cb74d87ff266b124f3a1', 'hex')),
  (32::bigint, decode('29cd3859439183091df02f6c0e0889b004be70d6a8f7a8acea6e1e275447234f1c0002bfb7602095c459b5123fb2de57', 'hex')),
  (33::bigint, decode('731b14c48be87da709531f57bf61e711a0fc4c0689c35d90a175d8945ef2bd8dccb448e94b3d958a2f2143144f317248', 'hex'))
), differences AS (
  (SELECT version, checksum FROM expected EXCEPT SELECT version, checksum FROM _sqlx_migrations WHERE success)
  UNION ALL
  (SELECT version, checksum FROM _sqlx_migrations EXCEPT SELECT version, checksum FROM expected)
)
SELECT NOT EXISTS (SELECT 1 FROM differences) AND NOT EXISTS (SELECT 1 FROM _sqlx_migrations WHERE NOT success) AS migrations_match \gset
\if :migrations_match
\else
  \echo 'Database migration versions/checksums do not match this release.'
  DO $$ BEGIN RAISE EXCEPTION 'Migration verification failed'; END $$;
\endif
