import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { tanstackRouter } from "@tanstack/router-plugin/vite";

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    tanstackRouter({
      target: "react",
      routesDirectory: "./src/app/routes",
      generatedRouteTree: "./src/app/routeTree.gen.ts",
      virtualRouteConfig: "./src/app/routes.ts",
      quoteStyle: "double",
      semicolons: true,
      routeTreeFileHeader: [
        "// biome-ignore-all lint: generated by TanStack Router",
      ],
    }),
    react(),
  ],
  resolve: {
    alias: {
      "@": "/src",
    },
  },
  server: {
    port: parseInt(process.env.VITE_PORT || "5173", 10),
    proxy: {
      // Blossom uploads are same-origin in production (Caddy proxies /upload
      // to the relay); this gives dev the same shape, so the client code has
      // exactly one path.
      "/upload": {
        target: "https://chat.creatorhive.ai",
        changeOrigin: true,
      },
    },
    strictPort: true,
  },
});
